# Generated by Django 3.0.8 on 2020-07-05 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('miniBlog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogger',
            name='email',
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_name',
            field=models.CharField(max_length=250, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blogger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miniBlog.Blogger', verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='blogger',
            name='bio',
            field=models.TextField(blank=True, default='Нет информации', max_length=500, verbose_name='Общая информация'),
        ),
        migrations.AlterField(
            model_name='blogger',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='blogger',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='blogger',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='blogmessage',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miniBlog.Blog', verbose_name='Блог'),
        ),
        migrations.AlterField(
            model_name='blogmessage',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='blogmessage',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author_name',
            field=models.CharField(max_length=100, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='blog_message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miniBlog.BlogMessage', verbose_name='Пост'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(verbose_name='Текст'),
        ),
    ]
