# Generated by Django 3.0.8 on 2020-07-06 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miniBlog', '0002_auto_20200705_2043'),
    ]

    operations = [
        migrations.RenameField('BlogMessage', 'description', 'text'),
    ]
