# Generated by Django 3.0.8 on 2020-07-06 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniBlog', '0003_auto_20200706_1734'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-create_date'], 'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AddField(
            model_name='blog',
            name='description',
            field=models.CharField(blank=True, max_length=500, verbose_name='Описание'),
        ),
    ]
