# Generated by Django 3.0.8 on 2020-07-06 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miniBlog', '0005_comment_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author_name',
        ),
    ]
